[package]
name = "text_byte_file"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magic-crypt = "3.1.13"

[profile.release]
strip = true

[[bin]]
name = "byfi"
path = "./src/main.rs"